# docker compose version which is currently 3.8
version: '3.8'
# services : is a list of our container
services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5173:5173'
